# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-04-02 18:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
    ]
