# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-04-02 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0004_auto_20210402_1848'),
    ]

    operations = [
    ]
