# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2021-04-04 17:42
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storm', '0005_auto_20210402_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='bigcategory',
            name='description',
            field=models.TextField(default='JonahYoo的个人网站，拥抱开源生活，崇尚不断学习，提升自我能力。', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='bigcategory',
            name='keywords',
            field=models.TextField(default='JonahYoo,技术,博客,Python,ML,DL,Linux', help_text='用来作为SEO中keywords,长度参考SEO标准', max_length=240, verbose_name='关键字'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default='JonahYoo的个人网站，拥抱开源生活，崇尚不断学习，提升自我能力。', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.TextField(default='JonahYoo的个人网站，拥抱开源生活，崇尚不断学习，提升自我能力。', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, verbose_name='描述'),
        ),
    ]
